---
title: "Step1: Read datasets from CMI-PB website and perform data harmoniation"
#format: html
#editor: visual
output:
  BiocStyle::html_document:
    toc: true
    toc_float:
        collapsed: true
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    code_folding: show
    number_sections: false
date: "2023-12-21"
---

## Download all data files

We manually downloaded data files manually from the following repositories: 
1) Raw prediction datasets: [CMI-PB https site](https://www.cmi-pb.org/downloads/cmipb_challenge_datasets/current/2nd_challenge/raw_datasets/). 
2) Processed training datasets for ID mapping: [CMI-PB https site](https://www.cmi-pb.org/downloads/cmipb_challenge_datasets/current/2nd_challenge/raw_datasets/). 

Alternatively, `RCurl` package can be used to download data files.

```{r}
## `codebase.R` installs required packages and all house keepinf functions
source(paste0(base_dir, "scripts/codebase.R"))


#base_dir = "/home/pramod/Documents/GitHub/second-challenge-prediction-dataset-preparation/"
base_dir = "../"

dir_data = paste0(base_dir, "data/")
dir_raw_prediction <- paste0(base_dir, "data/raw_datasets/prediction/")
```

## Read training data object to map feature IDs
```{r}
master_processed_training_data_obj = read_rds(paste0(dir_data, "master_processed_training_data.RDS"))

features_training_abtiter = rownames(master_processed_training_data_obj$abtiter_wide$batchCorrected_data)
features_training_plasma_cytokine_concentrations = rownames(master_processed_training_data_obj$plasma_cytokine_concentrations$batchCorrected_data)
features_training_pbmc_cell_frequency = rownames(master_processed_training_data_obj$pbmc_cell_frequency$batchCorrected_data)
features_training_pbmc_gene_expression = rownames(master_processed_training_data_obj$pbmc_gene_expression$batchCorrected_data)
```


```{r}
d2022_subject <- read_tsv(paste0(dir_raw_prediction, "2022BD_subject.tsv"))
d2022_specimen <- read_tsv(paste0(dir_raw_prediction, "2022BD_specimen.tsv"))

## create new object subject_specimen
d2022_subject_specimen <- d2022_specimen %>%
  left_join(d2022_subject) %>%
  mutate(timepoint = planned_day_relative_to_boost)

```
## Read experimental data
```{r}

```

